# Site settings
title: Sensock
email: sensock@gmail.com
url: "localhost:4000"
description: "Description of the sock. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: CF000F #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/sensockWearable
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: http://github.com/sensock

# Postal address (add as many lines as necessary)
address:
  - line: 101 College Street
  - line: Toronto, ON M5G 1L7

# Credits content
credits: 
  Imran J | Rashad A | Julien B

# Build settings
markdown: kramdown
permalink: pretty
